### ISSUE TITLE
want to know more

### ISSUE THREAD

**Issue by hftsai** [compomics/cellmissy#2]
Hi i would like to know more of cellmissy from this paper
https://www.nature.com/articles/srep42383

But the slides, binary and manual hyperlinks are all invalid.

Can you fix it so i can know more?

thank you.

**Comment by gsergeant** [comment]
Apologies, the file servers hosting this support data are having issues.

In the meantime I will try to access them and put copies in a folder here on Github.
I will let you know when it's done.

**Comment by gsergeant** [comment]
All the links should be working now. 
You can find the end-user zip for version 1.1.0  [here](https://github.com/compomics/cellmissy/blob/master/releases/CellMissy-1.1.0.zip) and the manual and other files mentioned in the readme in [this folder](https://github.com/compomics/cellmissy/tree/master/supportFiles).

Thank you for bringing this issue to my attention and please let me know if you encounter any further problems!

**Comment by hftsai** [comment]
Thank you!!
